language: java
jdk:
  - openjdk8
  - oraclejdk11
  - openjdk11
 
# Simulates a display
dist: xenial
services:
  - xvfb

addons:
  apt:
    packages:
      - at-spi2-core # against "Error retrieving accessibility bus address"
      - libwebkitgtk-3.0 # against "Please ensure Webkit with its Gtk 3.x bindings installed. Webkit2 API level preferred."
      
# runs "test" goal on default, which misses IT
script:
- mvn verify -B
 
# export the IT log file
after_failure:
  - if [ -f /home/travis/build/slothsoft/eclipse-maven-view/de.slothsoft.mavenview.it/target/surefire-reports/*.txt ]; then lynx -dump /home/travis/build/slothsoft/eclipse-maven-view/de.slothsoft.mavenview.it/target/surefire-reports/*.txt; fi
  - if [ -f /home/travis/build/slothsoft/eclipse-maven-view/de.slothsoft.mavenview.testplan/target/surefire-reports/*.txt ]; then lynx -dump /home/travis/build/slothsoft/eclipse-maven-view/de.slothsoft.mavenview.testplan/target/surefire-reports/*.txt; fi
